### ISSUE TITLE
Request for demo

### ISSUE THREAD

**Issue by Bhaney44** [algorand-devrel/wormhole-demo#1]
This looks really cool, but it isn't clear from the docs to me what this code does. I think it would be awesome if this is an easy to use API for bridging b/w blockchains and it would be very helpful if there was a video demonstration. That way, it would be more clear what this software is doing. Thanks!

**Comment by barnjamin** [comment]
Updated the README with how to run.

This was made for a hackathon, not really a thing meant for general purpose except to see how wormhole SDK is used.
